### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by Roiyaru** [SmartPack/SmartPack-Kernel-Manager#1]
Hello developer, I think this is a good app, but it doesn't seem to support Chinese, which is a disadvantage. I can help you improve your Chinese support. How can I get the original text for translation?

**Comment by sunilpaulmathew** [comment]
Thanks for the good suggestion @Roiyaru 
Its difficult to maintain the translations, thats why I havn't included yet. But if you can, please feel free to do it. The original English strings can be found [here](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values/strings.xml).
Also, you can actually copy a bunch of stuff from [this](https://github.com/Grarak/KernelAdiutor/blob/master/app/src/main/res/values-zh-rCN/strings.xml) file located at Grarak's official KA repo.

**Comment by Roiyaru** [comment]
It seems that there is a lot of content to be translated, but I will complete the Chinese translation as soon as possible.

**Comment by Roiyaru** [comment]
I tried to translate a small amount of text, I want to know if this translation can be displayed correctly and successfully in the software.
https://github.com/Roiyaru/Chinese-translation-support-library/blob/master/SmartPack-Kernel%20Manager

**Comment by sunilpaulmathew** [comment]
Please try the two attached apk files one by one and tell me which one worked for you (I hope at least one will work).
[apk1](https://transfer.sh/6Rnti/apk1.apk)
[apk2](https://transfer.sh/BZD0s/apk2.apk)

**Comment by Roiyaru** [comment]
Translation on apk1 is normal, apk2 can not display translation

**Comment by Roiyaru** [comment]
@sunilpaulmathew  Translation on apk1 is normal, apk2 can not display translation

**Comment by Roiyaru** [comment]
@sunilpaulmathew  Well, I will finish the transition as soon as possible

**Comment by sunilpaulmathew** [comment]
@Roiyaru 
I hope it will not be a tough task since a bunch of translations are already available in official KA repo, [here](https://github.com/Grarak/KernelAdiutor/blob/master/app/src/main/res/values-zh-rCN/strings.xml), though it is important to compare and make sure it's still same...

**Comment by Roiyaru** [comment]
@sunilpaulmathew  The Chinese translation seems to be complete. It seems that I only need proofreading translation.

**Comment by sunilpaulmathew** [comment]
@Roiyaru 
Link it to me, please. I'll find someone one of the telegram group or in xda

**Comment by Roiyaru** [comment]
@sunilpaulmathew  I didn't find the telegram group. Can you provide a link?

**Comment by sunilpaulmathew** [comment]
@Roiyaru 
I haven't stated a telegram group for the app. But, if you send me the translated file, either here or in my [personal telegram](https://t.me/sunilpaulmathew) chat, I shall request the help of other Chinese guys within my chat list (and also in other groups)...
