### ISSUE TITLE
[bug] Zram always showing even when its enabled.

### ISSUE THREAD

**Issue by Dark-Cod3r** [SmartPack/SmartPack-Kernel-Manager#10]
Hi. So zram is enabled by default but for some reason its not showing as enabled (saying not in range) in SPKM. I checked in ex kernel manager and zram showing enabled in it. Also i confirmed from diskinfo app, zram is enabled. Kindly fix this issue if possible. 
Screenshots attached. 
![Screenshot_2019-05-30-13-17-31-586_flar2 exkernelmanager](https://user-images.githubusercontent.com/6500557/58619061-7abb7680-82dd-11e9-8984-1b87dfeb8302.png)
![Screenshot_2019-05-30-13-17-20-881_com smartpack kernelmanager](https://user-images.githubusercontent.com/6500557/58619069-7ee79400-82dd-11e9-91dd-d77816613f42.png)
![Screenshot_2019-05-30-13-17-07-794_com smartpack kernelmanager](https://user-images.githubusercontent.com/6500557/58619071-7f802a80-82dd-11e9-93e7-b5919e7d3152.png)

**Comment by sunilpaulmathew** [comment]
@Dark-Cod3r 
Thanks for reporting. Its mostly because the Max zRAM size allowed in this app (not updated for a long) is 2048, which is below the actual zRAM value. If it is possible, try reduce zRAM to below 2048 and see if the slider is working fine? I shall increase the max limit to include your higher value, though I'm not fully sure about its consequences.

**Comment by Dark-Cod3r** [comment]
Yep (noticed that after posting here , it not a bug just a limitation i guess). Ex kernel manager by default has 2560 limit (thats why no issue in that app). 
Changing zram size to 2048 fixed the issue but for some reason mobile starts to lag. That's why i never mess with zram settings. Its not much of a big deal i guess (i am sure most people dont care about tweaking zram by their own) but i think if a feature exist it should be working properly (otherwise most people like me gonna think its a bug , which is not). Anyway thanks for the quick reply.👌 Great app so far.

**Comment by sunilpaulmathew** [comment]
I can also increase the higher limit to 2560 in the next update.
