### ISSUE TITLE
Control over all io blocks

### ISSUE THREAD

**Issue by NitroVenom** [SmartPack/SmartPack-Kernel-Manager#100]
This kernel manager should give control over all io blocks. One io block can be used to see current status of io. To change property of all io block this needs to be executed: 

for i in /sys/block/*/queue/[parameter you want to change, for example- iostats] 
do 
echo [value you want] > $i 
done

**Comment by sunilpaulmathew** [comment]
Not so easy from the app, like simple shell commands you wrote.  What if some blocks are read only?  What if the supported value ranges are different on different blocks. Thanks for the issue, anyway.

**Comment by NitroVenom** [comment]
Ok

**Comment by sunilpaulmathew** [comment]
@NitroVenom 
Reopening this issue as I got some new ideas to work on this.

**Comment by sunilpaulmathew** [comment]
Closing since this is already done. Feel free to reopen it, if you find any issues.
