### ISSUE TITLE
Some more gpu parameters

### ISSUE THREAD

**Issue by NitroVenom** [SmartPack/SmartPack-Kernel-Manager#101]
I also have some gpu parameters for adreno. They are- 

Gpu throttling = /sys/class/kgsl/kgsl-3d0/throttling 
Bus split = sys/class/kgsl/kgsl-3d0/bus_split 
Force no nap = /sys/class/kgsl/kgsl-3d0/force_no_nap 
Force rail on = /sys/class/kgsl/kgsl-3d0/force_rail_on
Force clk on = /sys/class/kgsl/kgsl-3d0/force_clk_on
Force bus on = /sys/class/kgsl/kgsl-3d0/force_bus_on

Note that all these only have 2 states, 0=off and 1=on. 
So, you can add a toggle instead of a number selection screen.

**Comment by sunilpaulmathew** [comment]
> I also have some gpu parameters for adreno. They are-
> 
> Gpu throttling = /sys/class/kgsl/kgsl-3d0/throttling
> Bus split = sys/class/kgsl/kgsl-3d0/bus_split
> Force no nap = /sys/class/kgsl/kgsl-3d0/force_no_nap
> Force rail on = /sys/class/kgsl/kgsl-3d0/force_rail_on
> Force clk on = /sys/class/kgsl/kgsl-3d0/force_clk_on
> Force bus on = /sys/class/kgsl/kgsl-3d0/force_bus_on
> 
> Note that all these only have 2 states, 0=off and 1=on.
> So, you can add a toggle instead of a number selection screen.

Thanks
& Any chance to get a proper title and a short description (if possible) for those parameters. Otherwise, I could get many questions (+ complaints) in future.

**Comment by sunilpaulmathew** [comment]
Name: GPU throttling 

Sysfs node: /sys/class/kgsl/kgsl-3d0/throttling 

Description: GPU throttling reduces the performance of GPU if the GPU gets hot.
