### ISSUE TITLE
Can't change I/O Scheduler

### ISSUE THREAD

**Issue by pudup** [SmartPack/SmartPack-Kernel-Manager#103]
Probably not a problem specific to this application, but SP along with all other kernel mod apps, except ElementalX, cannot change the I/O scheduler on my phone.
It seems to be an issue with not being able to change it while the storage is mounted. Although I don't know why EX is capable of changing it. I however don't want to use EX and I was wondering why SP cannot change it.

**Comment by sunilpaulmathew** [comment]
> Probably not a problem specific to this application, but SP along with all other kernel mod apps, except ElementalX, cannot change the I/O scheduler on my phone.
> It seems to be an issue with not being able to change it while the storage is mounted. Although I don't know why EX is capable of changing it. I however don't want to use EX and I was wondering why SP cannot change it.

Are you sure that EX really changes the Scheduler. Can you check it in command-line (not from app).

**Comment by pudup** [comment]
I'll do that not, but assuming exK cannot change it, is it just not possible to be changed?

**Comment by pudup** [comment]
Can confirm that exK manager does change the scheduler. It's changed at /sys/.../scheduler and both apps acknowledge the change

**Comment by sunilpaulmathew** [comment]
> te that this issue has ex

Thanks for testing. One more question. Can you check whether the changing scheduler is working from the command line (without using none of the apps)?

**Comment by pudup** [comment]
No I can't change it through the terminal, or via a root text editor either. The terminal returns no output but it fails to change. The text editor throws a permission denied error.

**Comment by NitroVenom** [comment]
Then mybe your kernel has a problem

**Comment by pudup** [comment]
> Then mybe your kernel has a problem

Except that other kernel apps don't have an issue changing it.
