### ISSUE TITLE
Switching to the "SmartPack" section sometimes causes a crash

### ISSUE THREAD

**Issue by BulletBlaster** [SmartPack/SmartPack-Kernel-Manager#116]
Steps to reproduce:

1. Switch to any other section
2. Switch to the "SmartPack" section
3. Repeat steps 1 and 2 until app crashes

Using version 16.8, can reproduce on both the F-Droid and Google Play versions.

**Comment by BulletBlaster** [comment]
Might be related to #104, hovewer I can reproduce it on the Google Play build too and having two or more entries in the "On boot" section doesn't fix it.

**Comment by sunilpaulmathew** [comment]
> Steps to reproduce:
> 
> 1. Switch to any other section
> 2. Switch to the "SmartPack" section
> 3. Repeat steps 1 and 2 until app crashes
> 
> Using version 16.8, can reproduce on both the F-Droid and Google Play versions.

Can you record a logcat and share with me? Thanks

**Comment by sunilpaulmathew** [comment]
> Might be related to #104, hovewer I can reproduce it on the Google Play build too and having two or more entries in the "On boot" section doesn't fix it.

Nope. On on boot section, there is a specific reason, which is however bit hard to fix. Crashing SmartPack page is, however, surprising.

**Comment by BulletBlaster** [comment]
> Can you record a logcat and share with me? Thanks

I think it's all that's relevant:

>11-18 18:36:17.215 24390 28821 E AndroidRuntime: FATAL EXCEPTION: pool-16-thread-1
>11-18 18:36:17.215 24390 28821 E AndroidRuntime: Process: com.smartpack.kernelmanager.release, PID: 24390
>11-18 18:36:17.215 24390 28821 E AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8809)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1608)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at androidx.drawerlayout.widget.DrawerLayout.requestLayout(Unknown Source:4)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at android.view.View.requestLayout(View.java:25390)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.requestLayout(Unknown Source:8)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$v.a(Unknown Source:28)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$f.b(Unknown Source:18)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at m2.i.D0(:1)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at r2.n0$a.d(:1)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at m3.b.b(:1)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at r2.n0.Z0(Unknown Source:5)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at r2.n0.A0(Unknown Source:0)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at m2.i$b.a(Unknown Source:27)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at m3.a.run(:1)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>11-18 18:36:17.215 24390 28821 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
>11-18 18:36:17.169  1446  1568 I chatty  : uid=1000(system) android.bg identical 6 lines
>11-18 18:36:17.169  1446  1568 W NotificationHistory: Attempted to remove conversation for locked/gone/disabled user 0
>11-18 18:36:17.220  1446  3088 W ActivityTaskManager:   Force finishing activity com.smartpack.kernelmanager.release/com.smartpack.kernelmanager.activities.NavigationActivity
>11-18 18:36:17.223  1446 28824 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
>11-18 18:36:17.257  2923  2923 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1748 android.content.ContextWrapper.bindService:756 com.google.android.libraries.gsa.launcherclient.i.c:14 com.google.android.libraries.gsa.launcherclient.LauncherClient.reconnect:107 com.google.android.libraries.gsa.launcherclient.LauncherClient.onStart:67 
>11-18 18:36:17.257  1446  2945 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:1000?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
>11-18 18:36:16.092  2841  3207 D TelephonyProvider: Using old permission behavior for telephony provider compat
>11-18 18:36:17.385  2569  2586 W System  : A resource failed to call release.

**Comment by sunilpaulmathew** [comment]
@BulletBlaster 
It doesn't look much useful. Can you please record and share a better one. Probably, with the help of [Logcat app](https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en&gl=US) (it will help you to view logs for a specific app). Since I'm now running a non-rooted device, I have limitations to do it here.
Thanks

**Comment by sunilpaulmathew** [comment]
@BulletBlaster I hope this issue is fixed as of v16.9? Can you confirm? Thanks

**Comment by Tomatoide** [comment]
It crashes at startup now

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6998)
	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1131)
	at android.view.ViewGroup.invalidateChild(ViewGroup.java:5207)
	at android.view.View.invalidateInternal(View.java:13679)
	at android.view.View.invalidate(View.java:13643)
	at android.view.View.invalidate(View.java:13627)
	at android.widget.TextView.updateTextColors(TextView.java:4091)
	at android.widget.TextView.setTextColor(TextView.java:3256)
	at com.smartpack.kernelmanager.activities.MainActivity$b.e(:3)
	at com.smartpack.kernelmanager.activities.MainActivity$b.a(:19)
	at b4.a.run(:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

**Comment by sunilpaulmathew** [comment]
@Tomatoide 
Is it a single event or crashes happened always? Also, are you on the latest version (v16.9). Can you try clearing cache? Thanks

**Comment by Tomatoide** [comment]
Only with latest update, clearing cache didn't help, opening the app it crashes immediately

**Comment by sunilpaulmathew** [comment]
> Only with latest update, clearing cache didn't help, opening the app it crashes immediately

No idea what's the hell is happening. Working fine on Android 10 (tested myself), 11 and 12 (reported by trusted users). I'll look for this issue later. Please stay on the old version till then. Thanks

**Comment by sunilpaulmathew** [comment]
> Only with latest update, clearing cache didn't help, opening the app it crashes immediately

[Can you please try this test build](https://www.dropbox.com/s/o8v6s7wal7yp007/com.smartpack.kernelmanager.apk?dl=0). Crashes on main activity should be crashed. Thanks.

**Comment by Tomatoide** [comment]
It works 👍

**Comment by sunilpaulmathew** [comment]
This issue should be fixed on latest versions. So, closing this issue. Thanks.
