### ISSUE TITLE
Performance Tweaks in quick setting not working and tabs problem

### ISSUE THREAD

**Issue by a0193143** [SmartPack/SmartPack-Kernel-Manager#118]
ROM: Resurrection Remix 8.7.2
Kernel: Project Infinity 4.4.294 EAS
SmartPack version: v16.9 and v17.0 (Both downloaded from F-Droid)

After v16.9 update, the Performance Tweaks in the quick setting tile not working anymore
![Screenshot_20211215-120211_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/32773311/146122438-b32b5eba-788e-4dd9-8d59-e2c53a31363d.png) ![Screenshot_20211215-120302_Nova7](https://user-images.githubusercontent.com/32773311/146122441-e7501606-621b-48f1-8b43-5825d2008b34.png)

And if I desabled some tabs under settings, the "Setting" will dissappeared.
![Screenshot_20211215-120324_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/32773311/146122443-a2493373-9bd3-4c17-8a0c-350cc490989b.png)

**Comment by sunilpaulmathew** [comment]
@a0193143 Thanks for reporting these issues.
Regarding the quick tile issue, have you tested other quick tiles (K-lapse; if your kernel supports, Scripts) as well. Also, can you tell me the exact behaviour of quick tiles on < v16.9. I mean, is they are simply inactive and greyed out. I'm not using a rooted device ATM (so, testing here is difficult).
Regarding the settings issue, I think it was here for a while. I have no clues to fix it (so, added a "**help wanted**" label to this issue).

**Comment by opusforlife2** [comment]
@sunilpaulmathew Specifically, the Backup menu toggle seems to cause the Settings menu entry to vanish as well. Since you're still on the settings page when this happens, you can easily see the entry being restored when you toggle Backups on again.

There are other examples too. The Overall and FAQ entries are also linked. Turning FAQ off seems to turn Overall off as well. And turning Overall back on turns FAQ on automatically.

**Comment by a0193143** [comment]
Seems these problems fixed in 17.2, I would close this issue.

**Comment by opusforlife2** [comment]
Indeed! The Settings toggle is no longer linked to the Backup toggle.

BTW, another linked pair: CPU and Custom Controls.
