### ISSUE TITLE
Kswapd thread 

### ISSUE THREAD

**Issue by lateautumn233** [SmartPack/SmartPack-Kernel-Manager#119]
Threads that control kswapd
Path: /proc/sys/vm/kswapd_threads
Default:1
About kswapd:https://www.halolinux.us/kernel-architecture/periodic-reclaim-with-kswapd.html

**Comment by sunilpaulmathew** [comment]
@lateautumn233 
Thanks. Can you suggest me a suitable title and description for this feature. Also, what about the possible values?

**Comment by lateautumn233** [comment]
Here is a specific introduction 

https://github.com/alk3p/android_kernel_xiaomi_sm8250/commit/7e78bc0ad238e41e940299c5c06baba0b3d99e4a#diff-d503e0c4ef59449a7b9dd9f14c3f88b35578cdec99edbd05970e0599faf1c324
