### ISSUE TITLE
Request to add a seekbar to change charging current. 

### ISSUE THREAD

**Issue by 1337Kamayuk** [SmartPack/SmartPack-Kernel-Manager#12]
So I would like to have an option to change the amount of current that is being supplied.
/sys/module/qpnp_smbcharger/parameters/default_hvdcp3_icl_ma 
/sts/module/qpnp_smbcharger/parameters/default_fastchg_current_ma
These are the 2 files that should be changed for changing the current supplied. I would be really happy if thy could add this in your app. Thank you!

**Comment by sunilpaulmathew** [comment]
@1337Kamayuk 
Are you still interested in this feature?
If so, I shall implement it...
