### ISSUE TITLE
Mediatek display color control (MTK GAMMA) (LiveDisplay) (KCAL analogue)

### ISSUE THREAD

**Issue by 7Soldier** [SmartPack/SmartPack-Kernel-Manager#124]
Hello again, sir. Can you please add this analogue for KCAL on mediatek devices.

1. Description:
Custom add-on for mediatek display manager that allows you to change display rgb calibration. This is analogue for KCAL, but without settings for saturation, contrast, etc., only for colors. Another name (used in config) is LiveDisplay.

2. Information:
Commit of this driver add-on - https://github.com/WyrdProject/kernel_xiaomi_mt6765/commit/9aae05d6a8ab030f0588b3ac7930019f14bfd81d
Range of values is 0-2000 of red, blue, green.

3. SysFS paths:
RGB control - /sys/devices/platform/mtk_disp_mgr.0/rgb

4. Content of SysFS paths:
RGB control - "2000 2000 2000" (red, green and blue values accordingly)

5. How to set new value:
echo "xxxx xxxx xxxx" > /sys/devices/platform/mtk_disp_mgr.0/rgb (for example "xxxx xxxx xxxx" can be "10 1500 938")

This is all information.
If you need something other write me.
Thanks!

**Comment by 7Soldier** [comment]
@sunilpaulmathew Hello. No. Only 0-2000 of every value (red, green and blue). But in can configured for decrease max value less 2000.
But full max is 2000.
Thanks.

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew Hello. No. Only 0-2000 of every value (red, green and blue). But in can configured for decrease max value less 2000. But full max is 2000. Thanks.

Hi, I'm extremely sorry for this long delay. Do you have time to test this feature. If so, [here](https://www.dropbox.com/s/o8v6s7wal7yp007/com.smartpack.kernelmanager.apk?dl=0) is a test build for you. Thanks.

**Comment by 7Soldier** [comment]
> > @sunilpaulmathew Hello. No. Only 0-2000 of every value (red, green and blue). But in can configured for decrease max value less 2000. But full max is 2000. Thanks.
> 
> Hi, I'm extremely sorry for this long delay. Do you have time to test this feature. If so, [here](https://www.dropbox.com/s/o8v6s7wal7yp007/com.smartpack.kernelmanager.apk?dl=0) is a test build for you. Thanks.

Hello, thanks. I'll try it now.

**Comment by 7Soldier** [comment]
@sunilpaulmathew 
Working fine, except bug with numbers less 10, but it s my problem, because on my device begonia (and only on it) for unkown reasons i have artefacts with numbers over 1990 and i need to hardcode it to +10.
Well, in general, this is all my problem, and everything works fine on your part, thank you!

**Comment by sunilpaulmathew** [comment]
@7Soldier 
Thanks a lot. Issue is closed. Will publish new version of app soon.
