### ISSUE TITLE
Confusing regarding CPU Type names

### ISSUE THREAD

**Issue by rnayabed** [SmartPack/SmartPack-Kernel-Manager#132]
Device: Xiaomi 11X (aliothin)
CPU: SD 870

When I used Franco Kernel Manager, the CPU section had 3 configurable types - `LITTLE`, `BIG` and `PRIME`.

However, SmartPack shows them as `LITTLE`, `MEDIUM`, `BIG`.

Is `MEDIUM` (SmartPack) and `BIG` (Franco) supposed to be the same?
Is `BIG` (SmartPack) and `PRIME` (Franco) supposed to be the same?

If yes then the it should report the names like Franco Kernel Manager as Qualcomm calls it as `PRIME` cores only.

**Comment by sunilpaulmathew** [comment]
Closing this issue as I don't think its a serious problem, rather just a different style of naming.
