### ISSUE TITLE
What is difference between free and pro version ?

### ISSUE THREAD

**Issue by ThieuMinh26** [SmartPack/SmartPack-Kernel-Manager#134]

**Comment by sunilpaulmathew** [comment]
@ThieuMinh26 
Absolutely nothing. Both are built from same source code. Only difference is, some features (such as SELinux control) are disabled in pro version to satisfy Google. It's (Pro version) basically to support the development of this project and motivate me a a bit :)

**Comment by n-ce** [comment]
Sad to see the free version removed from the store.
Store pkg size : 2MB
F-Droid pkg size : 4.5MB
