### ISSUE TITLE
Permission issue here

### ISSUE THREAD

**Issue by laltroweb** [SmartPack/SmartPack-Kernel-Manager#143]
I've a OnePlus6 (enchilada) with crdroid 9b4 (A13) and MCD kernel installed for free thanks to this app (so, Ty so much for this).
Installed fine, but some feature (eg backup) have a write a permission issue (like screen).
![Screenshot_20221116-223949_SmartPack-Kernel Manager](https://user-images.githubusercontent.com/16841896/202304818-9c1116ad-48a9-4270-af1f-589913e69c87.png)
![Screenshot_20221116-224119_SmartPack-Kernel Manager](https://user-images.githubusercontent.com/16841896/202304823-718e5838-9cf3-46e1-9831-0595deea0dd2.png)
![Screenshot_20221116-230608_SmartPack-Kernel Manager](https://user-images.githubusercontent.com/16841896/202304829-288d261d-3761-4ae3-89ed-8132beb2b93a.png)

Also, I've busybox installed via magisk, but here (second screen) ask me to install a busybox.

Anyway, great work and thanks again 👍☺️

**Comment by sunilpaulmathew** [comment]
@laltroweb 
Permission issue should be fixed in next update. Thank You.

**Comment by sunilpaulmathew** [comment]
@laltroweb 
Closing this issue as it already fixed. If you found more issues, please fee free to reopen it or start a new one. Thanks
