### ISSUE TITLE
Missing setting option

### ISSUE THREAD

**Issue by zputnyq** [SmartPack/SmartPack-Kernel-Manager#15]
My apology for bringing up this issue, since lately you need time for your life.
The issue is in the setting section. After I disabled some options (FAQ, contributors, init.d & build.prop editor) inside setting. The "setting" section is disappear & never get back unless data of spkm is cleared.
SPKM 8.5

Thanks
I really appreciate & no hurry, just take your time.

**Comment by sunilpaulmathew** [comment]
Thanks for reporting... I'll look for it later...

**Comment by VeleSila** [comment]
Same happens here.

**Comment by zputnyq** [comment]
@sunilpaulmathew 
Any detail that I can include for this issue ?
Logcat or something else

**Comment by sunilpaulmathew** [comment]
Not really...
I already reproduce it here...
Only need to find time to work it...

**Comment by sunilpaulmathew** [comment]
I think this issue is already fixed (according to my testing) from v9.13 onwards. Feel free to reopen this issue, if it is not true. Thanks

**Comment by zputnyq** [comment]
Yes, It's already fixed. Thanks a lot
Sorry I forgot to close this issue. I rarely open github & I rely on email notification for it
