### ISSUE TITLE
Low Memory Killer tab should be hidden if the device doesnt support it

### ISSUE THREAD

**Issue by ThieuMinh26** [SmartPack/SmartPack-Kernel-Manager#150]
As the title . LKM in android is obsolete , now most phone have LMKD but LKM section is still appear

**Comment by sunilpaulmathew** [comment]
@ThieuMinh26 
Sorry for the long delayed response. & can you suggest me a way to find whether LMKD  is supported or not so that I can disable that section in app.
Thanks in advance

**Comment by sunilpaulmathew** [comment]
> I mean hide lmk tab not lmkd , you can check it :
> 
> ```
> :/ # ls -a /sys/module/ | grep low
> 1|:/ #
> ```
> 
> And i dont think its possible to change lmkd config just by using echo ...

Hi again,
Thanks, & yes, I al so mean hiding LMK, not LMKD.

**Comment by sunilpaulmathew** [comment]
@ThieuMinh26 
I also found another way

> generic_x86_arm:/ # getprop init.svc.lmkd
> running

But not sure it's fully reliable.
