### ISSUE TITLE
I have added extra GPU support

### ISSUE THREAD

**Issue by opensourcefreak** [SmartPack/SmartPack-Kernel-Manager#159]
If you look at my fork, I have added support for exynos GPUs. Works with the galaxy S8 conformed, should be fine with other exynos-based platforms too.

**Comment by sunilpaulmathew** [comment]
> If you look at my fork, I have added support for exynos GPUs. Works with the galaxy S8 conformed, should be fine with other exynos-based platforms too.

Sorry for the long delay. I was (and still) in holidays. Do you minds initiating a PR? Thanks

**Comment by opensourcefreak** [comment]
I closed it because I figured it was too bad. You could change freqs, but gpubysy and freq graph was broken. You could not even change power policy. I will send more detailed info on the sysfs interfaces as well as some more ones that are specific to my kernel.

**Comment by opensourcefreak** [comment]
I was also on vaccation so this is a bit delayed too. The gpus that will will get support are the ones for samsung galaxy S7-S10. There is another KA fork with support for these but this one is much better as it is not abandoned. Details about what the sysfs does should be pretty clear and all the strings are corretct here: https://github.com/corsicanu/hKtweaks/blob/c57694bb4718d8d3c7df0fb11bbd8e1ca7434233/app/src/main/java/com/hades/hKtweaks/utils/kernel/gpu/GPUFreqExynos.java#L49

Also I am really bad at java so don't expect me to initiate prs for randowm stuff that I like too often.
