### ISSUE TITLE
Not able to identify Pixel 3A SD670 CPU small/big clusters

### ISSUE THREAD

**Issue by VeleSila** [SmartPack/SmartPack-Kernel-Manager#17]
SD670 has 6 small cores and 2 big cores; however, it is identified as 4+4. EX Kernel Manager can properly identify them.

Related kernels are: 
https://forum.xda-developers.com/pixel-3a/development/kernel-despair-kernel-t3942019
and
https://forum.xda-developers.com/pixel-3a/development/kernel-pixel-3a-xl-elementalx-1-01-t3931185

**Comment by sunilpaulmathew** [comment]
Thanks for reporting.
However, I need several sysfs paths and more time (too busy now) to make it work. Also, I do not own an SD670 device to test it myself.

**Comment by VeleSila** [comment]
Unfortunately, I'm not an expert on all these stuffs. The best I can do may be just help you to test it. Please let me know if I can give you any assistance.

**Comment by sunilpaulmathew** [comment]
@VeleSila 
Sorry for the long delay. However, I shall work on this now, if you help me to get some info from your Pixel 3A.

**Comment by VeleSila** [comment]
> @VeleSila
> Sorry for the long delay. However, I shall work on this now, if you help me to get some info from your Pixel 3A.

How may i help you?

**Comment by sunilpaulmathew** [comment]
Please show me the full screenshot of "Device" page of the app, or/and output of "cat /proc/cpuinfo" from a root shell.
Thanks
