### ISSUE TITLE
Audio setting not applied at startup

### ISSUE THREAD

**Issue by lucenera** [SmartPack/SmartPack-Kernel-Manager#20]
Hi, I use version 8.6 of your app.  There is a problem, if I set a certain gain for the headphones in the sound section, it is not applied at startup but only if I go back to the app and touch the bar on the gain.  I'm on AOSiP and OnePlus 5T.

**Comment by sunilpaulmathew** [comment]
Hi
You mean Apply on boot itself is not working, or only for sound settings? I'm also using an OP5T personally (but stock OOS), and sound gain applied successfully after booting. I doubt there is something preventing apply in boot services.

**Comment by lucenera** [comment]
I am referring only to the audio settings and to boot startup.  All other settings are normally applied at startup.  But now I switched to OmniROM and the problem occurred a couple of times now no longer.  I don't know what it depends on.  At the moment it seems to be solved by itself.
