### ISSUE TITLE
Profiles exported to .json format cannot be imported (SP reports "malformed json")

### ISSUE THREAD

**Issue by mrslezak** [SmartPack/SmartPack-Kernel-Manager#22]
Profiles exported to .json format cannot be imported (SP reports "malformed json").  I tried this in the latest 2 versions of SP same issue.  It can't recognize the .json profile it exports.  I.e. once saved and exported, it cannot be imported back into SP as a profile.   8.7 and 8.6 tested.  I know it worked many moons ago... maybe v8.3.

**Comment by sunilpaulmathew** [comment]
Thanks for reporting.
May be something wrong happened when I update the app to use external file manager. I'll look for it later.

**Comment by hexdra** [comment]
Still not working.

**Comment by sunilpaulmathew** [comment]
Thanks for raising this issue again.
It's actually working here. Only issue is, it have some incompatibility with some file manager apps (and also with the default documents UI). Please see this [video](https://www.dropbox.com/s/nbjs8001d0070yi/20-01-20-19-30-59.mp4?dl=0) for more information.
