### ISSUE TITLE
/sys/devices/system/cpu/cpuN/online getting its permissions changed

### ISSUE THREAD

**Issue by pascua28** [SmartPack/SmartPack-Kernel-Manager#23]
When changing CPU frequency for per-core policy devices (separate entries for /sys/devices/system/cpu/cpuN/cpufreq), like S5, it also sets /sys/devices/system/cpu/cpuN/online into read-only, breaking userspace hotplugs like mpdecision. Same thing happens when turning off mpdecision, where turning it back on doesn't allow mpdecision to work anymore cause the said sysfs entry is read-only.

**Comment by sunilpaulmathew** [comment]
Hi
You mean changing CPU frequencies? If so, how you change CPU frequencies in a per core basis? Which is beyond the scope of this app. Or do you mean something else? Can you be more specific?

**Comment by pascua28** [comment]
Sorry I haven't been clear enough. I didn't mean changing frequencies on a per-core basis. The problem is, when changing frequencies, /sys/devices/system/cpu/cpuN/online gets read only, which breaks mpdecision hot plugging. Need to manually change the permission to get hot plugging back

**Comment by sunilpaulmathew** [comment]
Thanks for the clarification.
I don't know how it happened for me. I never noticed that issue in my old S5, and current OP5T. Also, by inspecting the respective code (which is taken and nearly unmodified from official KA), I don't find anything changing the permission of "/sys/devices/system/cpu/cpu%s/online".
May be a kernel level issue?
