### ISSUE TITLE
Battery monitor notification

### ISSUE THREAD

**Issue by neekless** [SmartPack/SmartPack-Kernel-Manager#24]
Some popular kernel managers like EXKM and FK can show a notification showing battery details like screen on usage per hour etc. Do you think this is something you'll add?

**Comment by sunilpaulmathew** [comment]
Hi,
Thanks for the suggestion.
Honestly, I haven't think about that yet. Also, I don't think it's really necessary as it is readily available in the Android OS itself. 
Have a nice day.
