### ISSUE TITLE
not  able to identify Mi9T sdm730 and also small/big cluster

### ISSUE THREAD

**Issue by nosedive** [SmartPack/SmartPack-Kernel-Manager#25]
my Mi9T has a SDM730 CPU which is not identified nor CPU hotplug is available
I try to create a pull request to add support

**Comment by sunilpaulmathew** [comment]
Feel free to create a pull request. I do not have much time to work here at this moment.
Thanks in advance...

**Comment by sunilpaulmathew** [comment]
> my Mi9T has a SDM730 CPU which is not identified nor CPU hotplug is available
> I try to create a pull request to add support

Is this issue still valid? If so, we shall fix this.

**Comment by nosedive** [comment]
![Screenshot_20200409-142254_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/4619533/78895261-c8148280-7a6e-11ea-9a0f-987c0d0da6f0.png)
this is still valid with 10.4 

unfortunately my coding experience is far beyond yours, I've got no idea how to implement

**Comment by sunilpaulmathew** [comment]
> ![Screenshot_20200409-142254_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/4619533/78895261-c8148280-7a6e-11ea-9a0f-987c0d0da6f0.png)
> this is still valid with 10.4
> 
> unfortunately my coding experience is far beyond yours, I've got no idea how to implement

So, you have 1-6 little & 7-8 big clusters? If so, can you show me the screenshot of the about page of my app. Then, I'll try to fix it.
Thanks in advance...

**Comment by nosedive** [comment]
great, I've got the pic for you
the kernel identifies itself as SM6150 but has the codename sm7150
For better understanding take a look at the snapdragon 670, 710, 712, 720 and 730 at this Wikipedia 
https://en.m.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_systems-on-chip

![2020_04_09_060316](https://user-images.githubusercontent.com/4619533/78916599-ffdef280-7a8d-11ea-8121-409da803d1c0.png)

**Comment by sunilpaulmathew** [comment]
> great, I've got the pic for you
> the kernel identifies itself as SM6150 but has the codename sm7150
> For better understanding take a look at the snapdragon 670, 710, 712, 720 and 730 at this Wikipedia
> https://en.m.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_systems-on-chip
> 
> ![2020_04_09_060316](https://user-images.githubusercontent.com/4619533/78916599-ffdef280-7a8d-11ea-8121-409da803d1c0.png)

Nice, enough for me. Will try to fix it soon and send you a text build. If you have a telegram account, please contact me (sunilpaulmathew) or our discussion group (link in about page of app).
