### ISSUE TITLE
init.d script fails to allow new scripts to save, or old ones to be deleted

### ISSUE THREAD

**Issue by mrslezak** [SmartPack/SmartPack-Kernel-Manager#26]
I have tried every version of the software.  Once upon a time, I created an init.d script.  No matter how many versions I try, it always appears when I enable init.d.  I can't delete it, I can't edit it.  I cannot make a new init.d script (it won't save).

In the meantime before this is fixed, where is init.d saved?  I'm on Telegram @MattoftheDead using your kernel manager which is only missing the selection of thermal profiles.  I have to use init.d to change the thermal.  It is this simple.  An uninstall / resinstall still shows my script every time that was saved previously so I don't know if uninstalling SmartPack leaves files behind somewhere in /data/ or wherever.

chmod 644 /sys/class/thermal/thermal_message/sconfig
echo 10 > /sys/class/thermal/thermal_message/sconfig
chmod 444 /sys/class/thermal/thermal_message/sconfig

**Comment by sunilpaulmathew** [comment]
Thanks for the report. However, for me, it is more easy to add a switch to configure poco's thermal config, rather playing with the whole init.d stuff. I shall contact you in telegram later for testing? And, even if you uninstall SmartPack, a lot of stuff will remain retained inside internal storage ---> SP

**Comment by sunilpaulmathew** [comment]
So, the init.d page itself is replaced with a Script Manager, I think there is no more reason to retain this issue here. Closing now...
