### ISSUE TITLE
Why does it stop mpdecision?

### ISSUE THREAD

**Issue by Feinzer** [SmartPack/SmartPack-Kernel-Manager#3]
The app is executing "setprop ctl.stop mpdecision" when changing the CPU governor. Why is this necessary?

**Comment by sunilpaulmathew** [comment]
I am not completely sure. Only @Grarak know the exact reason as the respective code is a part of the base app, [Kernel Auditor](https://github.com/Grarak/KernelAdiutor).
However, I strongly believe that there should be some solid reasons for Grarak to turn off mpdecision upon changing a CPU Governor. For e.g., mpdecision might prevent the app from changing CPU Governors, at-least in certain devices (just a wild guess).

**Comment by Feinzer** [comment]
I see, I'll ask over that project or the forums. Thanks.
