### ISSUE TITLE
[Feature Request] adding rpmb partition & its tunables on "i/o scheduler" section

### ISSUE THREAD

**Issue by zputnyq** [SmartPack/SmartPack-Kernel-Manager#30]
rpmb partition is said to be unnecassary to tune, but I think it should go the same way with internal storage (mmcblk0) parameters since it is located there.
/sys/block/mmcblk0/mmcblk0rpmb

**Comment by sunilpaulmathew** [comment]
I don't know how much it is useful/dangerous. Any reference?

**Comment by zputnyq** [comment]
I don't know much actually.
What I'm afraid of is my device kernel also came with add_random set to 1 on this partition which i read somewhere that it can be dangerous

https://security.stackexchange.com/questions/166182/how-to-access-replay-protected-memory-block-rpmb-in-emmc

https://lwn.net/Articles/682276/

**Comment by zputnyq** [comment]
I close this feature request.
I believe the new custom control can handle this
