### ISSUE TITLE
CPUFreq: Updated to properly distinguish 4 Little/2 big core devices (need testing).

### ISSUE THREAD

**Issue by mrslezak** [SmartPack/SmartPack-Kernel-Manager#36]
More a comment here I'm not sure how the layout is supposed to look but under CPU it still just shows 4 big and 4 little cores on an 855 processor.  Which is really 3 big 1 prime and 4 little cores in EXKM and FK.  SmartPack is amazing BTW I recommend it to everyone.  The flasher and log dump was a great addition!

**Comment by sunilpaulmathew** [comment]
Yeah... I know,
But it needs some solid work. I'm already working with someone who own a OP7Tpro to work on this issue.
& This mentioned commit is not for your device.
Thanks for reporting, anyway...

**Comment by mrslezak** [comment]
Ah okay so you are adding for 855+ and not the 855, interesting.  Well it's good as is anyhow.

**Comment by sunilpaulmathew** [comment]
The situation is actually same, 
1 prime + 3 big + 4 little (isn't it)?

**Comment by mrslezak** [comment]
Yep the 855 and 855+ differ only in the default clock frequencies otherwise it's the same architecture.

**Comment by sunilpaulmathew** [comment]
@mrslezak 
I'm now working to update the CPU page to support the Prime cluster. If you are still around, I can send you test builds as I do not have a real device to test. Thanks in advance.
