### ISSUE TITLE
BUG: The app crashes on launch

### ISSUE THREAD

**Issue by martobg10** [SmartPack/SmartPack-Kernel-Manager#39]
Hi!

The app have root access from Magisk. When I click the app icon, the app opens and immediately crashes.

**More information:**
Alcatel Pixi 3 (7) 3G - 9002X
Android 4.4.2
Linux Kernel 3.4.67
Rooted with Magisk v20.3
Kernel Adiutor don't crash
I don't have Google apps because of 512MB RAM, shitty MTK processor, and shitty software optimization.

**ADB Logcat:**
https://my.pcloud.com/publink/show?code=XZwNaekZONNAzv9QJqmFAASJwqsck4sr2nay

**Edit:**
After installing Busybox from Magisk repo, the app crashes after "Collecting info".

**Comment by sunilpaulmathew** [comment]
@martobg10 
Thanks for the report. Root & BusyBox issues won't crash the app. I thoroughly go through the log, but haven't find the real issue. Unfortunately, upon every new release of android, it become exceedingly difficult to support old versions like your 4.4.x.
