### ISSUE TITLE
CPU core speeds not listed except 0Mhz when trying to select the speed frequency of the CPU cores

### ISSUE THREAD

**Issue by Errol1886** [SmartPack/SmartPack-Kernel-Manager#40]
The SmartPack Kernal Manager won't let select the speed of the maximum and minimum CPU cores. When I tap on "Maximum CPU frequency" or "Minimum CPU Frequency" I can only select 0MHz. No other CPU option clock speeds are listed. Also, in the "Profile Tasker" menu, it says "if you want to apply a profile at a specific event, such as launching an application, you have to use Tasker."

What do you mean you have to use "Tasker"? Are you talking about a separate app that needs to be downloaded from the Google Play Store? Because in the Profile Tasker menu of the SmartPack Kernal Manager app, there is no option to assign a custom profile to be used when launching an app.

**Comment by SmgKhOaRn** [comment]
@Errol1886 I don't know exactly about tasker, but it is sure that your kernel doesn't support to change your CPU freq.
Other things work fine?

**Comment by SmgKhOaRn** [comment]
@Errol1886 Ask to the kernel developer about this.

**Comment by Errol1886** [comment]
> @Errol1886 I don't know exactly about tasker, but it is sure that your kernel doesn't support to change your CPU freq.
> Other things work fine?

I am able to change the speed of the maximum and minimum CPU cores using other Kernal Manager apps. Only in SmartPack Kernal Manager I am unable to change the speed of the CPU cores. SmartPack only gives me the option of 0MHz to select for the CPU cores.

**Comment by sunilpaulmathew** [comment]
> > @Errol1886 I don't know exactly about tasker, but it is sure that your kernel doesn't support to change your CPU freq.
> > Other things work fine?
> 
> I am able to change the speed of the maximum and minimum CPU cores using other Kernal Manager apps. Only in SmartPack Kernal Manager I am unable to change the speed of the CPU cores. SmartPack only gives me the option of 0MHz to select for the CPU cores.

Thanks for reporting the issue & sorry for the delayed response from my side. 
Regarding the cpu frequency, it is not really an app issue. As I clearly written in my reply to your playstore comment, this app is not updated to work with devices using strange sysfs paths to manage cpu frequs/govs. Unfortunately, some recent xiaomi devices (including your one too) sadly on that category.  I need a lot of sysfs paths (such as "scaling_available_frequencies", "scaling_cur_freq", "scaling_available_governors") from your device as well as a lot more time to fix that issue. Also, I do not have any such devices in my hand to test it here.
Regarding tasker, yes, it is a mention about a separate app "Tasker".
