### ISSUE TITLE
Zram bugs

### ISSUE THREAD

**Issue by Emulatorer** [SmartPack/SmartPack-Kernel-Manager#43]
Zram option cannot adjust, always stuck in 512mb also not applying after a reboot.

### Phone Specs
Android 6.0.1
Mali-450 GPU Octacore
Rooted Via Magisk 20.4
SmartPack Kernel Manager v10.4

**Comment by sunilpaulmathew** [comment]
I'm not sure, why it is not stuck at 512 mb. Regarding the apply on boot issue, probably some system processes overwriting it. Please use a higher apply-on-boot value (it will probably work).

**Comment by Emulatorer** [comment]
Im using NFS Injector but this issue isn't happen on the original kernel auditor 🤔

**Comment by sunilpaulmathew** [comment]
> Im using NFS Injector but this issue isn't happen on the original kernel auditor

Well,
zRAM part is largely modified in this app mainly to accomodate compression type. Not sure it breaks something.

**Comment by Emulatorer** [comment]
Maybe there something useful in this logs why
Zram is not activated during reboot.

I'm using the latest version of smartpack kernel manager.

**Comment by sunilpaulmathew** [comment]
> Maybe there something useful in this logs why
> Zram is not activated during reboot.
> [logs.zip](https://github.com/SmartPack/SmartPack-Kernel-Manager/files/4479627/logs.zip)
> 
> I'm using the latest version of smartpack kernel manager.

Unfortunately, I don't find anything from the logs. Anyway, zRAM is a tricky part, and if your kernel doesn't want to tweak zRAM, better leave it as such.

**Comment by Emulatorer** [comment]
ok

**Comment by pudup** [comment]
Sorry for the year late reply but I only just experienced this myself on my phone. At least the not applying on reboot part. 

I fixed it by going to the "On Boot" page and moving the swapoff command to the top of the VM chain of commands. It was earlier at the bottom, below zram/0/reset and /zram0/disksize and max_comp_streams. 

Perhaps this can work for others too.
