### ISSUE TITLE
[Feature Request] Allow to dump activity logs

### ISSUE THREAD

**Issue by Emulatorer** [SmartPack/SmartPack-Kernel-Manager#44]
Just like Magisk Manager :)
![Screenshot_20200413-054351](https://user-images.githubusercontent.com/37603562/79080713-c9350080-7d49-11ea-8406-ad476dbe3234.png)

**Comment by sunilpaulmathew** [comment]
As far as understand, that is simply "/cache/magisk.log". You can still get the contents of that view by running "cat /cache/magisk.log" on SmartPack ---> Run Shell Command. If you are talking about something else, please feel free to correct me.
Thanks.

**Comment by Emulatorer** [comment]
Thanks for the explanation
