### ISSUE TITLE
[Feature Request] SmartPack Flasher show zip script log(result)

### ISSUE THREAD

**Issue by cxyzzz** [SmartPack/SmartPack-Kernel-Manager#45]
the SmartPack Flasher is very useful,but it's not show the zip script flash log.I can't know what happened with this.
![Screenshot_2020-04-13-18-01-57-422_com smartpack kernelmanager](https://user-images.githubusercontent.com/21036341/79112624-8d358600-7db1-11ea-88da-9ef5fe2e18fc.jpg)

**Comment by sunilpaulmathew** [comment]
@cxyzzz 
Thanks for the comment. It seems like flashing in your case is failed, most probably due to the lack of proper busybox binaries (that's why flashing log is empty). The issue will probably be fixed if you install a proper busybox binary. If you are interested, you may use my simple app available here. For any help, feel free to contact me in telegram (id: sunilpaulmathew).

**Comment by cxyzzz** [comment]
@sunilpaulmathew I'm using Magisk Manager,it's have a internal busybox at `/sbin/.magisk/busybox/`,could add this path support?

**Comment by cxyzzz** [comment]
@cxyzzz ![](https://i.imgur.com/cTB0935.jpg)

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew I'm using Magisk Manager,it's have a internal busybox at `/sbin/.magisk/busybox/`,could add this path support?

I know, & I'm now updating the app (will be released soon) to use Magisk busybox binaries. However, after initializing flashing command, my workarounds to use magisk busybox maynot work properly. So, it is ideal to have a standalone busybox binary installed.

**Comment by cxyzzz** [comment]
@sunilpaulmathew I add magisk busybox symlink to /system/xbin ,but it still have this issue.

**Comment by cxyzzz** [comment]
@cxyzzz this is magisk busybox have applets

``` bash
# home /sbin/.magisk/busybox/busybox
BusyBox v1.31.1-Magisk (2020-01-20 20:36:54 CST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --show SCRIPT
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, acpid, adjtimex, ar, arch, arp, arping, ash, awk, base64,
        basename, bbconfig, beep, blkdiscard, blkid, blockdev, brctl,
        bunzip2, bzcat, bzip2, cal, cat, chat, chattr, chcon, chgrp, chmod,
        chown, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp,
        cpio, crond, crontab, cttyhack, cut, date, dc, dd, deallocvt,
        depmod, devmem, df, dhcprelay, diff, dirname, dmesg, dnsd,
        dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed, egrep,
        eject, env, ether-wake, expand, expr, factor, fakeidentd, false,
        fatattr, fbset, fbsplash, fdflush, fdformat, fdisk, fgconsole,
        fgrep, find, findfs, flash_eraseall, flash_lock, flash_unlock,
        flock, fold, free, freeramdisk, fsck, fsck.minix, fsfreeze, fstrim,
        fsync, ftpd, ftpget, ftpput, fuser, getenforce, getopt, grep,
        groups, gunzip, gzip, hd, hdparm, head, hexdump, hexedit, hostname,
        httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave, ifplugd,
        ifup, inetd, inotifyd, insmod, install, ionice, iostat, ip, ipaddr,
        ipcalc, ipcrm, ipcs, iplink, ipneigh, iproute, iprule, iptunnel,
        kbd_mode, kill, killall, killall5, klogd, less, link, ln, loadfont,
        loadkmap, logread, losetup, ls, lsattr, lsmod, lsof, lspci, lsscsi,
        lsusb, lzcat, lzma, lzop, lzopcat, makedevs, makemime, man,
        matchpathcon, md5sum, mesg, microcom, mkdir, mkdosfs, mke2fs,
        mkfifo, mkfs.ext2, mkfs.minix, mkfs.reiser, mkfs.vfat, mknod,
        mkswap, mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat,
        mv, nameif, nanddump, nandwrite, nbd-client, nc, netstat, nice, nl,
        nmeter, nohup, nologin, nslookup, nuke, od, openvt, partprobe,
        paste, patch, pgrep, pidof, ping, ping6, pipe_progress, pivot_root,
        pkill, pmap, popmaildir, poweroff, powertop, printenv, printf, ps,
        pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readlink,
        readprofile, realpath, reboot, reformime, renice, reset, resize,
        restorecon, resume, rev, rfkill, rm, rmdir, rmmod, route, rtcwake,
        run-init, run-parts, runcon, rx, script, scriptreplay, sed,
        selinuxenabled, sendmail, seq, sestatus, setconsole, setenforce,
        setfattr, setfont, setkeycodes, setlogcons, setpriv, setserial,
        setsid, setuidgid, sh, sha1sum, sha256sum, sha3sum, sha512sum,
        showkey, shred, shuf, slattach, sleep, smemcap, sort, split,
        ssl_client, start-stop-daemon, stat, strings, stty, sum, svc, svok,
        swapoff, swapon, switch_root, sync, sysctl, syslogd, tac, tail,
        tar, tc, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time,
        timeout, top, touch, tr, traceroute, traceroute6, true, truncate,
        ts, tty, ttysize, tunctl, tune2fs, ubiattach, ubidetach, ubimkvol,
        ubirename, ubirmvol, ubirsvol, ubiupdatevol, udhcpc, udhcpc6,
        udhcpd, udpsvd, uevent, umount, uname, uncompress, unexpand, uniq,
        unix2dos, unlink, unlzma, unlzop, unshare, unxz, unzip, uptime,
        usleep, uudecode, uuencode, vconfig, vi, volname, watch, watchdog,
        wc, wget, which, whoami, whois, xargs, xxd, xz, xzcat, yes, zcat,
        zcip
```

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew I add magisk busybox symlink to /system/xbin ,but it still have this issue.

Have you tried "mount -o --bind"? I used that technique on my [flasher app](https://play.google.com/store/apps/details?id=com.smartpack.smartflasher) & it seems working.

**Comment by cxyzzz** [comment]
@sunilpaulmathew the magisk busybox mount not support -o:open_mouth:

**Comment by cxyzzz** [comment]
@sunilpaulmathew the smart flasher still have this issue.build it's show busybox error.so it's magisk busybox lose something?

```
## Flasher log created by Smart Flasher

** Preparing to flash Predator-lavender-20200413-06.zip...

** Path: '/storage/emulated/0/Download/Predator-lavender-20200413-06.zip'

** Checking for unzip binary! Available...
** Extracting zip file failed! *

** Flashing Failed! *
** Reason: Necessary BusyBox binaries not available! *
```

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew the smart flasher still have this issue.but it's show busybox error.so it's magisk busybox lose something?
> 
> ```
> ## Flasher log created by Smart Flasher
> 
> ** Preparing to flash Predator-lavender-20200413-06.zip...
> 
> ** Path: '/storage/emulated/0/Download/Predator-lavender-20200413-06.zip'
> 
> ** Checking for unzip binary! Available...
> ** Extracting zip file failed! *
> 
> ** Flashing Failed! *
> ** Reason: Necessary BusyBox binaries not available! *
> ```

The error only means extracting zip file to temporary directory failed, and thus flashing.
Can you try once again? I also got flasher failing occasionally, but worked fine after second attempt). Btw, can I have that zip file (to tets myself, if it is not a device specific stuff). Thanks.

**Comment by cxyzzz** [comment]
@sunilpaulmathew 

zip file link(**Be careful, this is a kernel file** )
https://t.me/predator_kernel/407

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew
> 
> zip file link(**Be careful, this is a kernel file** )
> https://t.me/predator_kernel/407

Well, it's definitely device specific. Thanks anyway... Have a nice day.
