### ISSUE TITLE
[features request] add information per option like L Speed have

### ISSUE THREAD

**Issue by Emulatorer** [SmartPack/SmartPack-Kernel-Manager#48]
Example:
![Screenshot_20200421-140954](https://user-images.githubusercontent.com/37603562/79831446-02b8dc00-83da-11ea-89b3-38b0b8d0ea6c.png)
![Screenshot_20200421-140951](https://user-images.githubusercontent.com/37603562/79831452-064c6300-83da-11ea-9daf-f9e69c80e203.png)

**Comment by sunilpaulmathew** [comment]
I think, we already have a description of most of the features (as titles/summaries)? If you are looking for an exact same kind of "info" icon along with each option, it won't happen to this app from my side as it is a really heavy task. To be honest, I don't have enough time to do that. So, closing this issue.

**Comment by Emulatorer** [comment]
![Screenshot_20200421-232100](https://user-images.githubusercontent.com/37603562/79883692-d24b5f00-8426-11ea-935e-abe1f25cdf46.png)
Can you add info about CPU set?
because I really don't know what cpu set can do
