### ISSUE TITLE
Some questions about busybox！

### ISSUE THREAD

**Issue by johanlike** [SmartPack/SmartPack-Kernel-Manager#50]
I have to say that this is a great project with great potential. Thank you for your hard work. I found some problems when using SmartFlasher. If android has a lower version of busybox or busybox without unzip modules. Even if newly installed buysbox1.31, it will not refresh normally. But EX Manager can. Therefore, I hope that SmartFlasher can use magisk path busybox. Or use the busybox that comes with the software . This will resolve this type of error.

**Comment by sunilpaulmathew** [comment]
I'm trying to use Magisj BusyBox binaries. But, unfortunately, it doesn't seem working nicely all the time. The only thing seems always working is to install a standalone BusyBox (so, made this app: https://play.google.com/store/apps/details?id=com.smartpack.busyboxinstaller).

**Comment by johanlike** [comment]
@sunilpaulmathew 
Yes, I have installed the latest busybox. But SmartFlasher is not recognized correctly. Normally, magisk's busybox must be available, because if there is no unzip module, then the magisk module cannot be installed normally. I checked your project code and found that the detection path of unzip is
[code](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/java/com/smartpack/kernelmanager/utils/tools/SmartPack.java#L64)
```
"/system /xbin/ unzip"
"/system/bin/unzip"
```
However, if the old version of busybox is installed before Android, the unzip function may not be complete. So I suggest adding a detection path. Using buybox from magisk can completely avoid this problem.
```
/sbin/.magisk/busybox/unzip
```

**Comment by Lennoard** [comment]
I'm not a Magisk guy but I have a question:
Does your `/sbin/.magisk/busybox/unzip` appear under `which -a unzip`?

**Comment by johanlike** [comment]
@Lennoard 
The test showed that it did not appear.
```
kali:/ # which -a unzip
/system/bin/unzip
/system/xbin/unzip

```

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew
> Yes, I have installed the latest busybox. But SmartFlasher is not recognized correctly. Normally, magisk's busybox must be available, because if there is no unzip module, then the magisk module cannot be installed normally. I checked your project code and found that the detection path of unzip is
> [code](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/java/com/smartpack/kernelmanager/utils/tools/SmartPack.java#L64)
> 
> ```
> "/system /xbin/ unzip"
> "/system/bin/unzip"
> ```
> 
> However, if the old version of busybox is installed before Android, the unzip function may not be complete. So I suggest adding a detection path. Using buybox from magisk can completely avoid this problem.
> 
> ```
> /sbin/.magisk/busybox/unzip
> ```

Actually, I'm checking that too ([here](https://github.com/SmartPack/SmartFlasher/blob/7bc9237d60172a6925a67bee41ee2a96da8f7c5b/app/src/main/java/com/smartpack/smartflasher/utils/Flasher.java#L62)), & loop mounting that path to /system/xbin. However, it is not working nicely always (don't know why).

**Comment by sunilpaulmathew** [comment]
> `which -a unzip`?

Nope

**Comment by johanlike** [comment]
@sunilpaulmathew 
I think it is possible to add a judgment option. When the first unzip cannot be used, try the other two paths of unzip until all the tests fail. Report related errors to users.

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew
> I think it is possible to add a judgment option. When the first unzip cannot be used, try the other two paths of unzip until all the tests fail. Report related errors to users.

Let me see.
