### ISSUE TITLE
profiles arent applying after boot

### ISSUE THREAD

**Issue by nasrrrr775** [SmartPack/SmartPack-Kernel-Manager#52]
when i make a profile and apply it, without reboot i notice my game(super mecha champions)run slower than before, so i tried to make the profile on boot and rebooted the phone, but nothing got applied, only went back to max cpu and max gpu settings that i dont even know how to change them in cpu and gpu section, iwant the profile to be applied so my phone dont heat upbalot knowing that i dont need max cpu usage to run the game(my phone is poco f1) but it seems broken and not applying anything to the turning setting for cpu and gpu... please help me or find fix for this bug,  and thanks for ur development time and ofc this is the best kernel manager i have ever met!.

**Comment by sunilpaulmathew** [comment]
Are you sure that you're profile created successfully (please check the details view)? I tried applying profile, both normally & on boot, and it worked as usual.

**Comment by nasrrrr775** [comment]
my issue is a bit more complicated, first when i make a profile and (as u wanted i checked detaols and my settings were in green there) i can apply them and yea i use app to monitor my cpu and it does the job but the problem is with gpu, the gpu dont take the kernel change and instead of being maxed out(everytime the app show me my gpu is overclocked to the highest end) the whole phone slow down and even antutu run gpi test poorly although i just downed its clock alittle bit by applying the profile, so i used to but the option( on boot )and checked the  section(on boot) in the app to show me the profile, but when i restart the phone, i open the app again to see all my cpu and gpu are maxed up again and my profile  settings arent applied as promised !!!now iam confused, iam also afraid its not the app issue but cmon why when i apply a profile without a boot gpu suddenly downgrade its performance??????!!!! and still this issue is taking my battery and time and iam using sesh kernel latest version with it!
thanks!

**Comment by Lennoard** [comment]
I'm so confused now.

**Comment by nasrrrr775** [comment]
iam more than you! i used old version named kerner adiutor and it has the same issue, if i want to adjust something i need to do it every time i boot my phone, iam worried about its temp that keep constant at 60-70c that was supposed to cool down after cpu workload reduction to 2400 instead of 2800(cpu speed) but no iam either facing hot temp or low temp with low performance gpu!!!

**Comment by sunilpaulmathew** [comment]
Controlling CPU/GPU related features are more headache. If you can, try enable the "Script" option in settings (sometimes it works).

**Comment by nasrrrr775** [comment]
well i enabled it but u need a script to begin with right? iam not that smart or have any experience making scripts so can i download them or creat them or what?;?!

**Comment by sunilpaulmathew** [comment]
It will automatically create a Script and execute it in boot, when you enable it.

**Comment by nasrrrr775** [comment]
hmm, but script of what? the corrent cpu and gpu settings or the profile that  i applied setting or the profile that i put(on boot) settings?

**Comment by sunilpaulmathew** [comment]
Whatever added to your profile

**Comment by nasrrrr775** [comment]
tried and apploed profile and put it(same profile )on boot then restarted my phone, when i entered the password immediatly went to cpu monitor to notice again that my cpu is working fully 2800 instead of 2356 in profile, nothing happened!!
btw i found a way to at least make(smc) the game i mentioned above, work smoothly with profile settings by applying profile before first time running the game after boot,it solved my issue but still, it didnt solve the main issue, and i hope u see why this happens with me,(my phone is poco f1, i have sesh kernel version 7.1, and i have this app, my rom is the offical rom 11)

**Comment by nasrrrr775** [comment]
since u seemed confused so much that my issue is rly strange i think i find the issue  and ofc iam the one who didn't notice it first, after searching i found that some kernels reset values auto, that means even if u made a script or profile, i won't apply after boot and if u applied them before boot ur (my gpu)stop working or being recognized by gaming apps(as far as i tested) so it was kernel issue and i wonder which kernel support free adjustments unlike sesh kernel, it seems that smartpack is useless with these kind of kernels since it can't do anything good (for kernel preview)but instead it ruin the kernel experience(that also do a lot of heat) but that was the whole issue problem....thanks for your responds to me and i hope ur not confused anymore in this issue!
thanks alot for developing this app considering its free and keep pushing forward!

**Comment by sunilpaulmathew** [comment]
Thanks & happy to know that you figure out the real issue. Closing this issue now.
