### ISSUE TITLE
Consistent wakelock feature issue in spkm v11.5

### ISSUE THREAD

**Issue by bhavtosh** [SmartPack/SmartPack-Kernel-Manager#58]
Hello,
Thanks for such a great kernel manager. It seems that wakelock feature is not updating "block wakelocks" list updated by the user because on next reboot only default wakelocks are disabled. 
I tried all versions from 10.8 till 11.5...Kindly look into it

**Comment by sunilpaulmathew** [comment]
> Hello,
> Thanks for such a great kernel manager. It seems that wakelock feature is not updating "block wakelocks" list updated by the user because on next reboot only default wakelocks are disabled.
> I tried all versions from 10.8 till 11.5...Kindly look into it

Just to make sure, have you set "Apply on boot" on the Wakelock page?

**Comment by bhavtosh** [comment]
Yes, that option is enabled and still spkm loads only its default "blocked" wakelocks

**Comment by sunilpaulmathew** [comment]
Okay, I'll look for it. Thanks for reporting. & Please be updated with the beta release on GitHub

**Comment by bhavtosh** [comment]
Sure, can i install a beta release over my installed v11.5 release?

**Comment by bhavtosh** [comment]
> 
> 
> Okay, I'll look for it. Thanks for reporting. & Please be updated with the beta release on GitHub

Sure, can i install a beta release over my installed v11.5 release?

**Comment by sunilpaulmathew** [comment]
> > Okay, I'll look for it. Thanks for reporting. & Please be updated with the beta release on GitHub
> 
> Sure, can i install a beta release over my installed v11.5 release?

I'm not sure. Some people reported issues related to app signing. By the way the latest stable is 11.7 & beta is 11.6.

**Comment by bhavtosh** [comment]
> 
> 
> > > Okay, I'll look for it. Thanks for reporting. & Please be updated with the beta release on GitHub
> > 
> > 
> > Sure, can i install a beta release over my installed v11.5 release?
> 
> I'm not sure. Some people reported issues related to app signing. By the way the latest stable is 11.7 & beta is 11.6.

I installed v11.7 & wakelock list issue is still there...

**Comment by bhavtosh** [comment]
Hi,
any update on this issue?

**Comment by sunilpaulmathew** [comment]
> Hi,
> any update on this issue?

Hi, Actually, I found a minor issue in the wake lock section and fixed it. But, I'm not fully sure it is not the sole reason for the issue. It is also likely that system settings overwrite app's on boot settings. Anyway, you may grab [this apk](https://www.dropbox.com/s/3xab451bik8ewa0/com.smartpack.kernelmanager.apk?dl=0) from my dropbox and check it out.

**Comment by bhavtosh** [comment]
> 
> 
> > Hi,
> > any update on this issue?
> 
> Hi, Sorry for not updating you. Actually, I found a minor issue in the wake lock section and fixed it. But, I'm not fully sure it is not the sole reason for the issue. It is also likely that system settings overwrite app's on boot settings. Anyway, you may grab [this apk](https://www.dropbox.com/s/3xab451bik8ewa0/com.smartpack.kernelmanager.apk?dl=0) from my dropbox and check it out.

Great, will test it out but let me give u feedback on Franco kernel behavior on this feature...It maintains list of blocked WLs even after reboot but overall WL functionality and UI is better in SPKM if this issue is fixed.

**Comment by sunilpaulmathew** [comment]
> > > Hi,
> > > any update on this issue?
> > 
> > 
> > Hi, Sorry for not updating you. Actually, I found a minor issue in the wake lock section and fixed it. But, I'm not fully sure it is not the sole reason for the issue. It is also likely that system settings overwrite app's on boot settings. Anyway, you may grab [this apk](https://www.dropbox.com/s/3xab451bik8ewa0/com.smartpack.kernelmanager.apk?dl=0) from my dropbox and check it out.
> 
> Great, will test it out but let me give u feedback on Franco kernel behavior on this feature...It maintains list of blocked WLs even after reboot but overall WL functionality and UI is better in SPKM if this issue is fixed.

Have you tested it? Any updates? Also, new beta (11.8) is released and available [here](https://github.com/SmartPack/SmartPack-Kernel-Manager/releases/tag/v11.8)

**Comment by bhavtosh** [comment]
Hi,
I did, havent tested it all but so far so good...

**Comment by bhavtosh** [comment]
Hi,
This issue is still not fixed in v12. Pls have a look...

**Comment by sunilpaulmathew** [comment]
> Hi,
> This issue is still not fixed in v12. Pls have a look...

Then, I do not have any idea left for now. I'll try to get more information from our telegram group. Thanks for the clarification anyway.

**Comment by bhavtosh** [comment]
![Screenshot_20200602-093500](https://user-images.githubusercontent.com/7352400/83482711-98a65300-a4be-11ea-83db-c2c091aa63d4.jpg)
Let me share some observations:
1. Boot script of spkm shows a path where it edits a wakelock file, as long as phone is ON, it works but on reboot the list empties, so it could be folder or file permissions issue.

**Comment by sunilpaulmathew** [comment]
> ![Screenshot_20200602-093500](https://user-images.githubusercontent.com/7352400/83482711-98a65300-a4be-11ea-83db-c2c091aa63d4.jpg)
> Let me share some observations:
> 
> 1. Boot script of spkm shows a path where it edits a wakelock file, as long as phone is ON, it works but on reboot the list empties, so it could be folder or file permissions issue.
> 2. Boeffla documentation says that below location is default:
>    /sys/class/misc/boeffla_wakelock_blocker/debug
> 
> But yr script is storing values in diff location? I dont know but hope that issues gets resolved.
> Thanks

1. When you set Apply on boot, app maintain a list of commands and apply when the Device boot up. That is how the whole apply on boot Settings work's. The on-boot tab looks in the photo looks perfectly fine.
2. That path is for the wakelocks disabled by default. The path we are working is correct. I don't see any reason to break it's functionality. Surprising no one else in our group reported this issue.

**Comment by bhavtosh** [comment]
> 
> 
> > ![Screenshot_20200602-093500](https://user-images.githubusercontent.com/7352400/83482711-98a65300-a4be-11ea-83db-c2c091aa63d4.jpg)
> > Let me share some observations:
> > 
> > 1. Boot script of spkm shows a path where it edits a wakelock file, as long as phone is ON, it works but on reboot the list empties, so it could be folder or file permissions issue.
> > 2. Boeffla documentation says that below location is default:
> >    /sys/class/misc/boeffla_wakelock_blocker/debug
> > 
> > But yr script is storing values in diff location? I dont know but hope that issues gets resolved.
> > Thanks
> 
>     1. When you set Apply on boot, app maintain a list of commands and apply when the Device boot up. That is how the whole apply on boot Settings work's. The on-boot tab looks in the photo looks perfectly fine.
> 
>     2. That path is for the wakelocks disabled by default. The path we are working is correct. I don't see any reason to break it's functionality. Surprising no one else in our group reported this issue.

Well, if all is fine then why disabled WLs shown in boot script r lost on reboot? 
Can u pls chk this with spkm test team?

**Comment by mrslezak** [comment]
I also noticed this issue actually and decided to move all the wakelocks blocked into the kernel instead.  This was some time ago though issue could be gone now.

**Comment by bhavtosh** [comment]
> 
> 
> I also noticed this issue actually and decided to move all the wakelocks blocked into the kernel default block list instead. This was some time ago though issue could be gone now.

What abt the list of WLs added by user? does this list now retained by spkm after boot?

**Comment by mrslezak** [comment]
Yes it looks retained on the latest version from the play store.  I'd say the issue is closed.
