### ISSUE TITLE
Light DOZE option...

### ISSUE THREAD

**Issue by bhavtosh** [SmartPack/SmartPack-Kernel-Manager#59]
Hello,
If possible could you add "Light DOZE option" under Overview section on landing screen? Many users use custom doze apps and these apps use light doze feature than deep feature, so the doze % of both modes will help users to see doze health of phone.
Kindly take this request as "good to have" feature...

**Comment by Lennoard** [comment]
As much as I like the idea I don't think it is "kernel related". It's framework related.

**Comment by sunilpaulmathew** [comment]
I'm worried that, adding options to tweak Android doze is against Google's policies and results in a ban of app from Playstore.

**Comment by bhavtosh** [comment]
> 
> 
> I'm worried that, adding options to tweak Android doze is against Google's policies and results in a ban of app from Playstore.

Oh, that I dont know but this option is abt just to simply read dumpsys and show duration of light doze just below deep doze...Naptime has this feature and its not kernel related. (Its ok if its not doable)
Kindly let me know, i will close this issue.

**Comment by sunilpaulmathew** [comment]
> > I'm worried that, adding options to tweak Android doze is against Google's policies and results in a ban of app from Playstore.
> 
> Oh, that I dont know but this option is abt just to simply read dumpsys and show duration of light doze just below deep doze...Naptime has this feature and its not kernel related. (Its ok if its not doable)
> Kindly let me know, i will close this issue.

I know, we used to have a switch to disable Doze (only disable & enabled) until Playstore release. You can still achieve it by importing [this script](https://github.com/SmartPack/ScriptManager/blob/master/examples/Doze.sh) Script Manager page. Again, it will only disable & enable on each execution.
