### ISSUE TITLE
Default settings of "blu_schedutil" issue

### ISSUE THREAD

**Issue by bhavtosh** [SmartPack/SmartPack-Kernel-Manager#60]
![Screenshot_20200514-084850_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/7352400/81889173-883a4100-95c0-11ea-83b9-04076849e8ad.png)

Hello,
I see these default settings every time I install spkm and select this, my fav cpu gov...
Are these really correct? Is there is no way to set cpu frequency in cpu gov? 

Please share a correct example to configure this gov!
Also is it good practice to leave STune Boost settings as it is (Default is off)? What exactly is it for?

**Comment by sunilpaulmathew** [comment]
It is supposed to be corrected, as it is directly reading from the driver. I don't have more idea about its tweaking, also about Sched Tune Boost settings. I'm just a normal user who always use default settings as much as possible. Probably, ask this question on a kernel or some tweaks discussion page?

**Comment by bhavtosh** [comment]
> 
> 
> It is supposed to be corrected, as it is directly reading from the driver. I don't have more idea about its tweaking, also about Sched Tune Boost settings. I'm just a normal user who always use default settings as much as possible. Probably, ask this question on a kernel or some tweaks discussion page?

Oh i see, do u know any forum of cpu governors because no one responds on xda and hardly no info on blu_schedutil tunables on google search... 
I will close this issue after yr reply.

**Comment by sunilpaulmathew** [comment]
> > It is supposed to be corrected, as it is directly reading from the driver. I don't have more idea about its tweaking, also about Sched Tune Boost settings. I'm just a normal user who always use default settings as much as possible. Probably, ask this question on a kernel or some tweaks discussion page?
> 
> Oh i see, do u know any forum of cpu governors because no one responds on xda and hardly no info on blu_schedutil tunables on google search...
> I will close this issue after yr reply.

Sadly no. Sorry.
