### ISSUE TITLE
Voltage values do not change...

### ISSUE THREAD

**Issue by bhavtosh** [SmartPack/SmartPack-Kernel-Manager#62]
![101181747_251455429511497_3045637936105127936_n](https://user-images.githubusercontent.com/7352400/83266594-ab7c0780-a1e0-11ea-90a7-f217eb3d42ea.png)

Hi,
Any idea why this feature is not working? These values dont change and if i change Global +- value then phone hangs. I tried v11.8 and 11.7 but no luck. 
Pls advice...

**Comment by sunilpaulmathew** [comment]
> ![101181747_251455429511497_3045637936105127936_n](https://user-images.githubusercontent.com/7352400/83266594-ab7c0780-a1e0-11ea-90a7-f217eb3d42ea.png)
> 
> Hi,
> Any idea why this feature is not working? These values dont change and if i change Global +- value then phone hangs. I tried v11.8 and 11.7 but no luck.
> Pls advice...

Your phone hanging means, it's definitely beyond the control of app. You're Kernel doesn't want to change the voltages (atleast in a way you are trying to do it).

**Comment by bhavtosh** [comment]
It should let changes values.

**Comment by sunilpaulmathew** [comment]
> It should let changes values.

Kernel is the boss. Nothing won't change without kernel support. App can't do any magic.

**Comment by bhavtosh** [comment]
U r right but if a kernel allows then spkm should be able to change values, right? I just meant to ask this only. Nowadays all kernels do let kernel mgr apps to allow changing values.
