### ISSUE TITLE
File translate

### ISSUE THREAD

**Issue by Fruity-0** [SmartPack/SmartPack-Kernel-Manager#66]
Hello. Can I somehow translate the language file into my native language and possibly send for implementation in the next update? I know that the translation system in the application has been implemented but I wanted to translate it on the computer.

**Comment by sunilpaulmathew** [comment]
> Hello. Can I somehow translate the language file into my native language and possibly send for implementation in the next update? I know that the translation system in the application has been implemented but I wanted to translate it on the computer.

Why not. Feel free to do it! Thanks in advance.

**Comment by Fruity-0** [comment]
I will translate the file in my free time so it will go a little bit. How do I finish where can I upload the file?

**Comment by sunilpaulmathew** [comment]
> I will translate the file in my free time so it will go a little bit. How do I finish where can I upload the file?

Take your time. And you can attach (or link) here once you finished. I'll take of the rest.

**Comment by Fruity-0** [comment]
I'm uploading the 30% translated file (for now) because I'll be adding the rest in the meantime. If a new version of "SmartPack-Kernel-Manager" comes out, if a language file is uploaded, I will check the current words and know what to improve immediately during work. I think it won't interfere too much.

[LINK](http://31.6.70.6/pliki/newtone/pliki/stringPL.xml)

**Comment by sunilpaulmathew** [comment]
> I'm uploading the 30% translated file (for now) because I'll be adding the rest in the meantime. If a new version of "SmartPack-Kernel-Manager" comes out, if a language file is uploaded, I will check the current words and know what to improve immediately during work. I think it won't interfere too much.
> 
> [LINK](http://31.6.70.6/pliki/newtone/pliki/stringPL.zip)

Hi,
Thank you very much for your efforts. I'm currently too busy with person things. But, I'll definitely make a test build with your string as soon as I can (most probably next week).

**Comment by Fruity-0** [comment]
Okay, take your time, I just sent it because it will be a while before I'm finished, and when some new test version comes out sooner, I'll also check for any character encoding errors in my native language (ą, ę, ś, etc.) and possibly get rid of them during further work.

**Comment by sunilpaulmathew** [comment]
> Okay, take your time, I just sent it because it will be a while before I'm finished, and when some new test version comes out sooner, I'll also check for any character encoding errors in my native language (ą, ę, ś, etc.) and possibly get rid of them during further work.

Hi, sorry for the long delay. Can you test the translation on this [build](https://www.dropbox.com/s/3xab451bik8ewa0/com.smartpack.kernelmanager.apk?dl=0)? Please let me know if the link died before you managed to get it. Have a nice day.

**Comment by Fruity-0** [comment]
Okay, I downloaded it, checked it and everything seems to be working fine so I'm going to do the rest. Thanks and Regards.

**Comment by sunilpaulmathew** [comment]
> Okay, I downloaded it, checked it and everything seems to be working fine so I'm going to do the rest. Thanks and Regards.

Great. Thank You very much

**Comment by sunilpaulmathew** [comment]
> Okay, I downloaded it, checked it and everything seems to be working fine so I'm going to do the rest. Thanks and Regards.
May I have your email id registered for this GitHub account. If so, I will give you authorship for your contributions.

**Comment by sunilpaulmathew** [comment]
> Okay, I downloaded it, checked it and everything seems to be working fine so I'm going to do the rest. Thanks and Regards.

May I have your email id registered for this GitHub account. If so, I will give you authorship for your contributions.

**Comment by Fruity-0** [comment]
OK, but I don't know how to do it, I need to find out how to register it.

**Comment by Fruity-0** [comment]
Is it about this option?
![Screenshot_1](https://user-images.githubusercontent.com/31104533/90442790-7befe380-e0db-11ea-859e-d27c4b3e0d53.jpg)

Or something completely different?

**Comment by sunilpaulmathew** [comment]
> OK, but I don't know how to do it, I need to find out how to register it.

I mean, you must be used an email address when you create your GitHub  address? Probably, the same address where you will notifications from GitHub.

**Comment by Fruity-0** [comment]
Something is not working for me, something was a mess if I wanted to create a repository link and the file was outdated.
I thought the leg should be done all general but only partially (a few lines in the file), or I did something wrong.
I will be sending updates in zip packets as I do so far as I don't want to mess up more there.

**Comment by sunilpaulmathew** [comment]
> ckets as I do so far as I don't want t

Okay, please do whatever is more convenient for you. And, I have no idea about what happened there.

**Comment by Fruity-0** [comment]
I don't know how it works on GitHub yet, so for now I will be sending packages. Maybe someday I will learn because I guess it is well done for the sake of order in the source files of a given project.

**Comment by Fruity-0** [comment]
I apologize in advance for typos, my English is poor.
Updating the file, (finished 100% theoretically), because part of the line is left original (in English) for better understanding or temporarily. I will add minor corrections over time, but this will happen later, when I manage to replace the official kernel in my phone. These are far-reaching plans, because you have to be cautious about this and you can go back to the official software.
The special characters in the file (%s) were left untouched as they are related characters as far as I can remember. If there are errors in the text encoding or worse in operation, please let me know.
The file has been replaced so the url is the same.

[Link 100%](http://31.6.70.6/pliki/newtone/pliki/stringPL.zip)

**Comment by sunilpaulmathew** [comment]
> I apologize in advance for typos, my English is poor.
> Updating the file, (finished 100% theoretically), because part of the line is left original (in English) for better understanding or temporarily. I will add minor corrections over time, but this will happen later, when I manage to replace the official kernel in my phone. These are far-reaching plans, because you have to be cautious about this and you can go back to the official software.
> The special characters in the file (%s) were left untouched as they are related characters as far as I can remember. If there are errors in the text encoding or worse in operation, please let me know.
> The file has been replaced so the url is the same.
> 
> [Link 100%](http://31.6.70.6/pliki/newtone/pliki/stringPL.zip)

Hi,
Thank you very much for the great work.
I'll soon release a new beta update with your translation included. Your efforts are really appreciated.
Have a nice evening

**Comment by sunilpaulmathew** [comment]
> I apologize in advance for typos, my English is poor.
> Updating the file, (finished 100% theoretically), because part of the line is left original (in English) for better understanding or temporarily. I will add minor corrections over time, but this will happen later, when I manage to replace the official kernel in my phone. These are far-reaching plans, because you have to be cautious about this and you can go back to the official software.
> The special characters in the file (%s) were left untouched as they are related characters as far as I can remember. If there are errors in the text encoding or worse in operation, please let me know.
> The file has been replaced so the url is the same.
> 
> [Link 100%](http://31.6.70.6/pliki/newtone/pliki/stringPL.zip)

Included in the latest beta. You can get it from [here](https://github.com/SmartPack/SmartPack-Kernel-Manager/releases/tag/v13.1).

**Comment by Fruity-0** [comment]
Welcome back.
I have one question.
What do these characters mean and how does the compiler see them? I do not see them in the application, hence my question.


PS:


Is this information for the beginning and end of the text?

![Screenshot_1](https://user-images.githubusercontent.com/31104533/92419274-cf9a9d80-f16c-11ea-9741-ab3ed0f33d58.jpg)

**Comment by Fruity-0** [comment]
Update 08-09-2020

-language fixes

[Link_08-09-2020](http://31.6.70.6/pliki/newtone/pliki/stringPL%2808-09-2020%29.zip)

**Comment by sunilpaulmathew** [comment]
> mation for the start and end of the text, and m

"\n" means a line break. Please retain it whenever you see it. Also, please retain other special characters such as "%s". They are all important.

**Comment by sunilpaulmathew** [comment]
> Update 08-09-2020
> 
> -language fixes
> 
> [Link_08-09-2020](http://31.6.70.6/pliki/newtone/pliki/stringPL%2808-09-2020%29.zip)

Thank you.

**Comment by Fruity-0** [comment]
Welcome back.
I am currently not using the Play Store but external sites (e.g. Apkpure) to install the application and I have noticed that there are new versions of xapk and apks (supposedly resource installers) including Smart-Pack. I noticed that in these versions (currently v13.4) there is no translation implemented or something is not working properly for me. In the version posted on GitHub (v13.1) here, the translation file worked fine.

Do I only need to install the apk file? and could it be related to not working?
![1](https://user-images.githubusercontent.com/31104533/93538923-a25da480-f94f-11ea-839a-e6e59d312d86.jpg)
![2](https://user-images.githubusercontent.com/31104533/93538931-a5589500-f94f-11ea-8142-88a6cee58fd1.jpg)

**Comment by sunilpaulmathew** [comment]
@Fruity-0 
That is really strange. Anyway, instead of downloading from an unofficial source, can you try the one from my [GitHub release page](https://github.com/SmartPack/SmartPack-Kernel-Manager/releases)? Either, latest (13.4) or the one before (13.3) will be fine. Ideally, install after uninstalling the old one. Thank you!

**Comment by Fruity-0** [comment]
I was installing from unknown sources because temporarily unable to find the download on GitHub (dropdown arrow :-D). I installed it and everything seems to work as it should.

Just out of curiosity:
1. In the photo below (the underlined option) I did not find the translation line in the strings.xml file?
![2](https://user-images.githubusercontent.com/31104533/93638383-7990ea00-f9f7-11ea-8340-a7a456f69fc3.jpg)

2. I'm trying to find my mistake in translating this description.
Can the lack of these signs (photo below) cause an error?
![Screenshot_1](https://user-images.githubusercontent.com/31104533/93638546-c4126680-f9f7-11ea-964e-93f0853886fe.jpg)
![1](https://user-images.githubusercontent.com/31104533/93638571-ca084780-f9f7-11ea-8ce9-7ac5a1fff3d8.jpg)

**Comment by Fruity-0** [comment]
Update 26-09-2020
-Translate the following lines

[LINK](http://31.6.70.6/pliki/newtone/pliki/stringPL%2826-09-2020%29.zip)

**Comment by sunilpaulmathew** [comment]
> I was installing from unknown sources because temporarily unable to find the download on GitHub (dropdown arrow :-D). I installed it and everything seems to work as it should.
> 
> Just out of curiosity:
> 
> 1. In the photo below (the underlined option) I did not find the translation line in the strings.xml file?
>    ![2](https://user-images.githubusercontent.com/31104533/93638383-7990ea00-f9f7-11ea-8340-a7a456f69fc3.jpg)
> 2. I'm trying to find my mistake in translating this description.
>    Can the lack of these signs (photo below) cause an error?
>    ![Screenshot_1](https://user-images.githubusercontent.com/31104533/93638546-c4126680-f9f7-11ea-964e-93f0853886fe.jpg)
>    ![1](https://user-images.githubusercontent.com/31104533/93638571-ca084780-f9f7-11ea-8ce9-7ac5a1fff3d8.jpg)

Extremely sorry for the delayed reply. You can't translate lines with "translatable="false" flag. The second photo is one such example. The first one can be translatable. The respective strings are as follows.
    <string name="enable_onboot">Enable On Boot</string>
    <string name="enable_onboot_message">On boot settings are disabled! App won\'t do anything when device boot!</string>

**Comment by sunilpaulmathew** [comment]
> Update 26-09-2020
> -Translate the following lines
> 
> [LINK](http://31.6.70.6/pliki/newtone/pliki/stringPL%2826-09-2020%29.zip)

Thank you!

**Comment by Fruity-0** [comment]
I have searched the file and cannot find this line. Maybe something with the file is wrong, or deleted (which is a bit weird), or there is a different version of the "strings" file that I got from Smart-Pack applications. :-/

**Comment by sunilpaulmathew** [comment]
> I have searched the file and cannot find this line. Maybe something with the file is wrong, or deleted (which is a bit weird), or there is a different version of the "strings" file that I got from Smart-Pack applications. :-/

You won't! Because that string is flagged as translatable="false". The in-built translator will always hide such strings.
https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/73f669a8d74ad982385e619c8e7f3ca839c6ccf5/app/src/main/res/values/strings.xml#L1126

**Comment by Fruity-0** [comment]
Regarding this: {<string name = "about_me" translatable = "false" ...} it's all ok.
My last post was only about this sentence {### The first one can be translatable. The respective strings are as follows. ###} I don't know how to quote the selected text on GitHub)

**Comment by Fruity-0** [comment]
fg

**Comment by Fruity-0** [comment]
Regarding this: {<string name = "about_me" translatable = "false" ...} it's all ok.
My last post was only about this sentence {### The first one can be translatable. The respective strings are as follows. ###}
PS:
I don't know how to quote the selected text on GitHub)

**Comment by Fruity-0** [comment]
I noticed support that the POEditor site for translation purposes. Can I continue translating on this site after creating a new account?

**Comment by sunilpaulmathew** [comment]
> I noticed support that the POEditor site for translation purposes. Can I continue translating on this site after creating a new account? Does it work or is it better to post here on GitHub?

Feel free to do it. I already uploaded your latest translation there. Also, extremely sorry for not letting you know about this change (I was too busy to manage all these things, and real-life reasons).

**Comment by Fruity-0** [comment]
>extremely sorry for not letting you know about this change (I was too busy to manage all these things, and real-life reasons).
It's okay, I don't look at it and forget it more than once.

Pre-translated, maybe confused something on the page, if something didn't work with characters or text length etc, I will make corrections.

**Comment by Fruity-0** [comment]
Hello. 
With version 16.3, the currently translated language has disappeared from English. With version 16.4 downloaded from GitHub, translation is already working. 
1.  Is this a mistake I made while translating?
2.  On the site, although I translated 100% once, i still write 97%, maybe I spelled the words wrong, I need to check it.

**Comment by sunilpaulmathew** [comment]
> Hello.
> With version 16.3, the currently translated language has disappeared from English. With version 16.4 downloaded from GitHub, translation is already working.
> 
> 1. Is this a mistake I made while translating?

No way. No changes in the polish strings made between v16.3 to v16.4. Probably, something else is wrong?
