### ISSUE TITLE
Avoid apply on boot and creating SP folder if not needed

### ISSUE THREAD

**Issue by opusforlife2** [SmartPack/SmartPack-Kernel-Manager#68]
I don't have any Apply on Boot settings configured. But when I restart my phone, Smartpack shows a notification saying "Apply on boot" and creates the folder SP in internal storage. Both of these are unneeded in my case.

**Comment by Lennoard** [comment]
I suggest creating a master "apply on boot" switch in the app settings (not SP settings). Currently there are too many apply on boot switches whose value must be evaluated in order to take this decision not to do anything on boot.

**Comment by sunilpaulmathew** [comment]
> not SP settings

Looks like a big job. we have to think more.

**Comment by Lennoard** [comment]
It could be something like "disable run on start up".
[Example here](https://github.com/Lennoard/SysctlGUI/blob/0106beefbded6e68da54fb08e444587d7f60f0ec/app/src/main/kotlin/com/androidvip/sysctlgui/activities/SettingsActivity.kt#L126).

**Comment by sunilpaulmathew** [comment]
> It could be something like "disable run on start up".
> [Example here](https://github.com/Lennoard/SysctlGUI/blob/0106beefbded6e68da54fb08e444587d7f60f0ec/app/src/main/kotlin/com/androidvip/sysctlgui/activities/SettingsActivity.kt#L126).

You're right. I got the idea...

**Comment by sunilpaulmathew** [comment]
A switch is added in Settings page to disable the entire on-boot service
ca8d33169e25aa43a95f3cb71bd42dbd8551576c
