### ISSUE TITLE
Fast Run

### ISSUE THREAD

**Issue by GiantWaffle** [SmartPack/SmartPack-Kernel-Manager#70]
Hi,

This isn't really an "issue".  I just don't know whether to use the function or not.  I searched both the XDA thread and Googled it and cannot find it.  But my Kernel obviously supports it, since I see the option.

In the "Low Memory Killer" section, right near the top, there is a setting that can be Enabled called "Fast Run".

What (specifically) is this setting related to and what exactlybdoes Enabling it do, please?

Thank You Very Much!

**Comment by Lennoard** [comment]
It's [definetelly in the framework sources](https://android.googlesource.com/kernel/msm/+/android-6.0.1_r0.74/drivers/staging/android/lowmemorykiller.c#71) but no clear indication of its purpose though. It appears to be part of adaptive LMK.

**Comment by GiantWaffle** [comment]
Do you know, has anyone tested it and seen any results (good or bad)?

Thanks

**Comment by GiantWaffle** [comment]
Hi,

Just FYI, immediately after my last comment, I enabled it to try it out.  Everything seemed to work fine, except I started having trouble torrenting, even though my Internet worked fine.

Sometimes it would transfer, but much slower and most times the torrents just stopped transferring.

I disabled Fast Run and torrents work great again!

Maybe this info will help a bit in figuring out what it's supposed to be for? :-)

TTYL

**Comment by Lennoard** [comment]
Perhaps it should demand more testing. I don't believe that torrenting is a good test example because of its natural volatility (seed / leech)

**Comment by GiantWaffle** [comment]
Hi,

Just FYI, I wasn't trying to test it when I torrented.  It's just what I noticed in normal usage of my phone is all.  And different torrents were the same.

I agree it isn't a good testing method.  I just wanted to report what I did notice hoping it might help a little bit maybe if you ever did check into it. :-)

Thanks
