### ISSUE TITLE
Feature request: Add lower options for IO readahead

### ISSUE THREAD

**Issue by eddie-LA** [SmartPack/SmartPack-Kernel-Manager#77]
High amounts of I/O readahead has been proven to be detrimental to latency on devices with fast flash memory, and that it important considering low latency is often the measure of good user experience rather than high throughput. 

Outright disabling readahead yields ~5% more speed. However, we can't make readahead lower than 128kb with Smartpack... I roll with 64kb personally for the loading time reduction but that is *still* not accessible via Smartpack.

Consider allowing for a full range of readahead options - from 128kb lower to disabled completely for those of us that want it?

**Comment by sunilpaulmathew** [comment]
@eddie-LA 
Thanks for raising this issue.
I can make it low if it is not dangerous. How much lower values you recommend? 64, 0 or something else?

**Comment by eddie-LA** [comment]
Yes, 64 is perfect 👍
Sorry for the late response :)
I updated to latest beta but min is still 128kb..? Do I need to clear app data?
