### ISSUE TITLE
I/O Readahead min still 128kb

### ISSUE THREAD

**Issue by eddie-LA** [SmartPack/SmartPack-Kernel-Manager#79]
Like the title suggests, even after clearing all data and starting anew Smartpack shows a configurable minimum of 128kb instead of 64 or 0 on latest beta. 
Here's a screenshot:
![Screenshot_20200924-233140](https://user-images.githubusercontent.com/28909420/94197247-308cda00-febe-11ea-8bd8-0c64168f29e4.png)

**Comment by sunilpaulmathew** [comment]
I'm extremely sorry to update you. Due to some policy violation issues, SPKM was removed from Playstore, and later resubmitted as new app. Here is the new link
https://play.google.com/store/apps/details?id=com.smartpack.kernelmanager.release
& ReadAhead minimum value is now 64.

**Comment by eddie-LA** [comment]
Nah, don't be sorry! :) 
Thanks for replying! I will close the issue now.
