### ISSUE TITLE
cpu core turns back on

### ISSUE THREAD

**Issue by EmadP** [SmartPack/SmartPack-Kernel-Manager#82]
when I turn off cpu cores manually, they turn back on in 2 seconds.I am using pop kernel for Xperia xz1.

**Comment by sunilpaulmathew** [comment]
Somehow, the cores are not allowed to turn off in your device (in fact, in most modern devices including my). App is really helpless, unless your kernel developer managed to find some workaround (please do not ask me how). Please consider that feature more like a monitor. Thanks for the understanding.

**Comment by EmadP** [comment]
thanks for the quick reply and great app.

**Comment by Fruity-0** [comment]
hj
