### ISSUE TITLE
bug I can't switch  on/off adreno idle feature 

### ISSUE THREAD

**Issue by djemilbakhti** [SmartPack/SmartPack-Kernel-Manager#85]
smart pack kernel manager send Y as parameters
require a send 1 or 0 to work 
![Screenshot_20201205-102434_Trebuchet](https://user-images.githubusercontent.com/39235831/101239006-911d6c00-36e4-11eb-84e0-16dd7e27fb8b.png)
![Screenshot_20201205-102530_Trebuchet](https://user-images.githubusercontent.com/39235831/101239008-937fc600-36e4-11eb-9e9f-8c0423e49743.png)

**Comment by sunilpaulmathew** [comment]
@djemilbakhti 
Hi, thanks for raising the issue.
I think the original AdrenoIdler uses "N" and "Y" for disable/enable. Is the one in your kernel is probably modified by the developer?
I can fix it easily if you check and tell me the values are changed in the respective path even after sending "y" or "N"  (instead of 1 or 0). Can you?

**Comment by djemilbakhti** [comment]
> @djemilbakhti
> Hi, thanks for raising the issue.
> I think the original AdrenoIdler uses "N" and "Y" for disable/enable. Is the one in your kernel is probably modified by the developer?
> I can fix it easily if you check and tell me the values are changed in the respective path even after sending "y" or "N" (instead of 1 or 0). Can you?

this is patch adreno idler source code : https://github.com/silont-project/kernel_xiaomi_onclite/commit/4ec61d8054e6bd22f0f5636bc62b340869e1abb9#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6

**Comment by sunilpaulmathew** [comment]
> > @djemilbakhti
> > Hi, thanks for raising the issue.
> > I think the original AdrenoIdler uses "N" and "Y" for disable/enable. Is the one in your kernel is probably modified by the developer?
> > I can fix it easily if you check and tell me the values are changed in the respective path even after sending "y" or "N" (instead of 1 or 0). Can you?
> 
> this is patch adreno idler source code : [silont-project/kernel_xiaomi_onclite@4ec61d8#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6](https://github.com/silont-project/kernel_xiaomi_onclite/commit/4ec61d8054e6bd22f0f5636bc62b340869e1abb9#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6)

I have nothing to do with it (or I have no capacity to deal with Kernel source). What I'm asking to you is
1. Enable that switch in app (ofcourse, it won't work).
2. Read the value of the sysfs (shown in the second screenshot) path and tell me if it is 1 or 0.

Thanks

**Comment by djemilbakhti** [comment]
> > > @djemilbakhti
> > > Hi, thanks for raising the issue.
> > > I think the original AdrenoIdler uses "N" and "Y" for disable/enable. Is the one in your kernel is probably modified by the developer?
> > > I can fix it easily if you check and tell me the values are changed in the respective path even after sending "y" or "N" (instead of 1 or 0). Can you?
> > 
> > 
> > this is patch adreno idler source code : [silont-project/kernel_xiaomi_onclite@4ec61d8#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6](https://github.com/silont-project/kernel_xiaomi_onclite/commit/4ec61d8054e6bd22f0f5636bc62b340869e1abb9#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6)
> 
> I have nothing to do with it (or I have no capacity to deal with Kernel source). What I'm asking to you is
> 
> 1. Enable that switch in app (ofcourse, it won't work).
> 2. Read the value of the sysfs (shown in the second screenshot) path and tell me if it is 1 or 0.
> 
> Thanks
![Uploading Screenshot_20201206-193334.png…]()

**Comment by djemilbakhti** [comment]
> > > @djemilbakhti
> > > Hi, thanks for raising the issue.
> > > I think the original AdrenoIdler uses "N" and "Y" for disable/enable. Is the one in your kernel is probably modified by the developer?
> > > I can fix it easily if you check and tell me the values are changed in the respective path even after sending "y" or "N" (instead of 1 or 0). Can you?
> > 
> > 
> > this is patch adreno idler source code : [silont-project/kernel_xiaomi_onclite@4ec61d8#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6](https://github.com/silont-project/kernel_xiaomi_onclite/commit/4ec61d8054e6bd22f0f5636bc62b340869e1abb9#diff-4f57324cc52e69a61182ce37aea22845592c41a05e0eee6e56fa1a3833389da6)
> 
> I have nothing to do with it (or I have no capacity to deal with Kernel source). What I'm asking to you is
> 
> 1. Enable that switch in app (ofcourse, it won't work).
> 2. Read the value of the sysfs (shown in the second screenshot) path and tell me if it is 1 or 0.
> 
> Thanks

![Screenshot_20201206-193334](https://user-images.githubusercontent.com/39235831/101289106-b7353000-37fa-11eb-9094-28b37a135b36.png)

**Comment by djemilbakhti** [comment]
Is show 1

**Comment by sunilpaulmathew** [comment]
> Is show 1

Great
That means, driver is indeed enabled. The issue is only on the display status. Will fix in next update.
Thanks

**Comment by sunilpaulmathew** [comment]
> Is show 1
If you wish, you can probably test this [attached apk](https://www.dropbox.com/s/9tse8288dvs6f3d/com.smartpack.kernelmanager.apk?dl=0).
**Please Note**: This is a beta-build. If you're on PlayStore version (stable), you will see two SPKM icons after installing this one due to the different package id.
