### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by krathalan** [SmartPack/SmartPack-Kernel-Manager#9]
Consider publishing the app on F-Droid -- I would love to be able to get automatic updates, as I don't use Google Play or Google Play Services. I believe it fits all of their inclusion criteria (https://f-droid.org/docs/Inclusion_Policy/). 

You can read more here:
- https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md
- https://f-droid.org/docs/Build_Metadata_Reference/

**Comment by sunilpaulmathew** [comment]
Thanks for the suggestion. This app is not published in Google Playstore, but have it's own auto update mechanism (upon launching the app, it will check for an update). Regarding fdroid, I'm not sure at this moment mainly due to the fact that this app is a fork of Kernel auditor, and don't want to make trouble to its developer.

**Comment by krathalan** [comment]
Oh, my apologies -- I mistook the "get it on Google play" button for the donation package to be for the kernel manager.

As for forks, F-Droid welcomes them and there are forks for many apps, some of which even remove donation-only feature restrictions. You can look at Phonograph and Vinyl as an example of this.

**Comment by sunilpaulmathew** [comment]
Only, the donation package, to support the development, is published in PlayStore. And, I know, there are many forks available in F-Droid, which remove the donation restrictions. Although there is no legal issues on it as per GPL, I consider it is highly unfair to the original developer, that prevents me from publishing this app on any app store. Sorry.

**Comment by DMSalesman** [comment]
@krathalan I see that the app is now available on Google Play.  In light of this, could you consider publishing it on F-Droid as well?
