### ISSUE TITLE
Which CPU governor to choose?

### ISSUE THREAD

**Issue by JFMugen** [SmartPack/SmartPack-Kernel-Manager#93]
Hey! 

I don't want to adjust every small setting so I just wanted to choose one from Governor list. But all of them look pretty much same except powersave. Is there a list that I can see the difference? Tried to look through here and google but couldn't find an answer :/ 

What I want to achieve is, prioritizing battery life but when I start to use (which is rarely, maybe 5-10 time per day) give a smooth experience.

**Comment by pudup** [comment]
This doesn't really belong here, but if you're on an HMP kernel, then Interactive, Conservative and Ondemand are your best choices.
