### ISSUE TITLE
Mediatek Mali GPU support?

### ISSUE THREAD

**Issue by rama982** [SmartPack/SmartPack-Kernel-Manager#96]
Current gpu frequency path :
```
$cat /sys/kernel/debug/ged/hal/current_freqency | cut -f2 -d ' '
299000
```
Read available GPU freq
```
$cat /proc/gpufreq/gpufreq_opp_dump | awk '{printf $4 "\n"}' | cut -f1 -d ","
950000
925000
900000
...
...
...
```
Lock GPU frequency :
```
echo 902000 > /proc/gpufreq/gpufreq_opp_freq
```
Unlock GPU frequency :
```
echo 0 > /proc/gpufreq/gpufreq_opp_freq
```

**Comment by sunilpaulmathew** [comment]
@rama982 
Sorry for the delayed reply. Also, it looks more complicated and very specific to some devices (especially, the values like Lock GPU frequency).  I have to check to incorporate this in the app, without making many changes in the current setup.

**Comment by rama982** [comment]
I can only confirm that this setup is in the current Helio series and Mediatek dimensity series with mali gpus.
